// ERZEUGT — nicht von Hand ändern.
// Quelle: openspec/changes/archive/ · Erzeuger: scripts/generate-release-entries.ts
// Neu erzeugen: pnpm release:entries (läuft auch über prebuild).
import type { ReleaseEintrag } from "../types/release";

export const RELEASE_EINTRAEGE: ReleaseEintrag[] = [
  {
    slug: "2026-08-31-titelbild-bestand-auf-dev",
    datum: "2026-08-31",
    titel: "Der Bestand auf DEV: warum ein Seed-Lauf ihn nicht heilt",
    linear: "AGE-599",
    aenderungen: [
      "Der Bestandsabsatz nennt die **gemessenen Zahlen vom 31.08.** statt einer allgemeinen Aussage.",
      "Er nennt die **Herkunft**: Spiegel (AGE-576), nicht Seed-Lauf.",
      "Er sagt für beide Skripte einzeln, **warum sie nicht greifen**.",
      "Er spricht ein **SHALL NOT** gegen das Löschen als Seed-Vorbereitung aus — die Stelle, an der diese Änderung tatsächlich schützt.",
      "Er hält die **Entscheidung vom 31.08.** fest: DEV bleibt, PROD wird nicht angefasst, ein vollständiger Neuaufbau ist ein eigener Vorgang.",
      "Nebenbei: `traegt` → `trägt` (in AGE-665 durchgerutscht).",
    ],
  },
  {
    slug: "2026-08-31-titelbild-anforderung-nachziehen",
    datum: "2026-08-31",
    titel: "Die Titelbild-Anforderung sagt wieder, was gebaut ist",
    linear: "AGE-665",
    aenderungen: [
      "**Die Verzeichnis-Karte kommt in die Aufzählung** — aus drei Bauteilen werden vier. Sie hält die Regel längst; die Anforderung führt das nach, sie verlangt nichts Neues.",
      '**Die Vorschauen bekommen eine eigene Klausel**, nicht einen fünften Aufzählungspunkt: „Eine Vorschau SHALL dieselbe Regel tragen wie die Fläche, die sie vorwegnimmt." Über die Eigenschaft formuliert, nicht über die zwei Namen — sonst ist die nächste Vorschau wieder ein eigener Vorgang.',
      '**Der Feed bleibt ausgeschlossen, aber mit dem richtigen Grund.** Er ist die einzige Fläche, die noch beschneidet (`aspect-[3/1]` **mit** `object-cover`). Der Ausschluss ruht damit auf einer offenen Entscheidung — AGE-664 — und nicht mehr auf „anderes Bildmaterial".',
      "**Der Seed-Absatz geht in die Vergangenheitsform** und behält seine gemessene Zahl. Ergänzt um den Zustand, der wirklich noch offen ist: der **Bestand**.",
      "**Die Bucket-Zahlen werden als datierter Beleg gekennzeichnet** (Stand 25.08.), nicht als fortlaufende Zusage.",
    ],
  },
  {
    slug: "2026-08-31-composer-abbruch",
    datum: "2026-08-31",
    titel: "Ein begonnener Beitrag lässt sich wieder verwerfen",
    linear: "AGE-670",
    aenderungen: [
      '**Der Composer bekommt einen Weg zurück.** Neben „Posten" steht künftig „Abbrechen": der Entwurf wird verworfen und der Composer klappt zu.',
      '**Verworfen wird alles auf einmal** — Text, Video-Link samt aufgeklapptem Feld, Sichtbarkeit zurück auf „Mitglieder", der Veröffentlichungszeitpunkt zurück auf „sofort", die gewählten Bilder, eine stehende Bildfehlermeldung und die gewählten Themen.',
      "**Ein erneutes Aufklappen beginnt leer**, nicht beim alten Entwurf.",
    ],
  },
  {
    slug: "2026-08-30-geplante-beitraege",
    datum: "2026-08-30",
    titel: "Einen Beitrag jetzt schreiben und später live schalten",
    linear: "AGE-667",
    aenderungen: [
      'Im Composer steht neben „Veröffentlichen" ein Weg, den Beitrag **für einen Zeitpunkt zu planen** — Datum **und** Uhrzeit.',
      'Bis dahin sieht ihn **nur der Verfasser**, mit der Markierung „geplant für …". Niemand sonst — keine Admin-Einsicht, keine Freigabe durch andere.',
      'Der Verfasser kann bis zum Zeitpunkt **ändern, den Zeitpunkt verschieben oder ganz zurücknehmen** (auf „sofort" stellen oder löschen).',
      "Ist der Zeitpunkt erreicht, erscheint der Beitrag im Feed, als wäre er in diesem Moment geschrieben worden — **oben**, nicht an der Stelle seines Schreibdatums.",
      "Für alles Bestehende ändert sich **nichts**: ein Beitrag ohne Planung verhält sich wie heute.",
    ],
  },
  {
    slug: "2026-08-28-sidebar-pill",
    datum: "2026-08-28",
    titel: "Beide Leisten klappen über denselben halben Pill am Rand ein",
    linear: "AGE-638",
    aenderungen: [
      "**Ein Bauteil statt zweier.** Ein halber Pill am Innenrand jeder Leiste, der über die Kante hinausragt, gespiegelt an beiden. Er klappt ein und aus.",
      "**Oben an beiden**, auf Höhe der Kopfzeile (Donalds Entscheidung).",
      "**Immer sichtbar**, nicht erst beim Darüberfahren.",
      "**Die untere Einklapp-Zeile links entfällt.** Die Feedback-Zeile darüber bleibt, wo sie ist — sie kam in AGE-566 aus einem eigenen Grund dorthin.",
      "**Die Sprechblase im eingeklappten rechten Rail bleibt klickbar.** Sie ist zugleich der Ungelesen-Melder, den `design-system/spec.md:1372` verlangt; eine grosse Fläche, die aussieht wie ein Knopf und nicht reagiert, wäre schlechter als eine Redundanz. Der Pill ist das **einheitliche** Bauteil, nicht das einzige.",
    ],
  },
  {
    slug: "2026-08-28-release-notes-modal",
    datum: "2026-08-28",
    titel: "Release-Notes im zentrierten Modal lesen, mit Screenshots",
    linear: "AGE-632",
    aenderungen: [
      "Eine Release-Note auf `/neues` ist anklickbar und öffnet sich **mittig als Modal**, mit Scroll-Sperre und Fokus-Falle.",
      "Eine Release-Note kann **Bilder** tragen. Sie hängen am archivierten Change, entstehen zur Bauzeit wie die Eintragsliste selbst und werden mit dem Bündel ausgeliefert — kein Upload-Weg, keine Migration, kein Bucket.",
      "Der Hinweis in der Glocke führt weiterhin auf `/neues`, aber mit **geöffneter** Note statt auf die blosse Liste.",
      "Die Liste bleibt, was sie ist: alle zugestellten Notes, das Jüngste zuerst.",
    ],
  },
  {
    slug: "2026-08-28-rail-breakpoint-xl",
    datum: "2026-08-28",
    titel: "Die rechte Leiste dockt an `xl` an — auch dort, wo die Spec noch `lg` sagt",
    linear: "AGE-652",
    aenderungen: [
      "Einer bindet die Schwelle an die Anforderung, die sie festlegt.",
      "Einer trennt die **gespeicherte Vorliebe** von ihrer **angedockten Darstellung**. Nur die zweite ist breitengebunden; Persistenz, Trennung vom Zustand der Navigation und die Toleranz gegenüber fehlendem Speicher gelten bei jeder Breite. Ohne diesen Absatz las sich der erste so, als sei unterhalb von `xl` auch die Vorliebe ausser Kraft — beide Reviewer haben genau das gelesen.",
    ],
  },
  {
    slug: "2026-08-28-neuigkeiten-archiv",
    datum: "2026-08-28",
    titel: 'Neuigkeiten-Fläche: ein Archiv für Zugestelltes und für „nicht relevant"',
    linear: "AGE-636",
    aenderungen: [
      '**Ein Eintrag steht in genau einem von zwei Zuständen: offen oder archiviert.** Archiviert wird er auf zwei Wegen — durch **Zustellung** (endgültig) oder durch die Markierung **„nicht relevant"** (rücknehmbar).',
      '**Ein zweites Kästchen je Zeile: „nicht relevant".** Es nimmt den Eintrag aus der Liste *und* aus der laufenden Auswahl — ein Eintrag, den man gerade als belanglos markiert, darf nicht angehakt im Entwurf landen.',
      "**Eine neue Tabelle `release_entry_skips`** hält die markierten Slugs. Ein Slug, ein Admin, ein Zeitpunkt — mehr nicht.",
      '**Ein aufklappbares Archiv** unter der Liste, zugeklappt beginnend, mit der Zahl im Kopf. Es nennt zu jedem Eintrag den Grund und trägt bei „nicht relevant" den Weg zurück.',
      '**`teileAuf()` ersetzt `nochNichtAngekuendigt()`**: dieselbe Rechnung, aber sie gibt **beide** Hälften zurück statt nur der einen. Die Zusage „ein Entwurf darf nichts verstecken" bleibt wörtlich erhalten und wird weiter geprüft.',
    ],
  },
  {
    slug: "2026-08-28-emoji-und-zeitstempel-im-chat",
    datum: "2026-08-28",
    titel: "Emoji-Auswahl und Zeitstempel in der Nachricht",
    linear: "AGE-645",
    aenderungen: [
      '**Emoji-Auswahl in der Sendezeile.** Ein Schalter im Eingabefeld öffnet ein Feld mit rund 1900 Emoji, nach Gruppen sortiert und **auf Deutsch durchsuchbar** — „Herz", „grün", auch „gruen". Vollständig mit der Tastatur bedienbar. Der Datensatz wird erst beim ersten Öffnen geladen und belastet den Seitenaufbau nicht.',
      "**Jede Nachricht trägt ihre Uhrzeit**, in der Zeitzone des Betrachters. Der volle Zeitpunkt steht im Tooltip.",
      '**Tagesmarker zwischen den Tagen** — „Heute", „Gestern", sonst Wochentag oder Datum. Der Tag steht einmal über der Gruppe statt an jeder Blase.',
      "**Getippte Emoticons werden beim Senden zu Emoji**: `:-)` wird 🙂, `<3` wird ❤️. Bewusst nur eine kleine Liste, und mit Wortgrenzen — Adressen, Hausnummern und Beträge wie `<3.000 Euro` bleiben unangetastet.",
      "Ältere Nachrichten werden **nicht** nachträglich verändert. Die Ersetzung wirkt auf das, was neu geschrieben wird.",
    ],
  },
  {
    slug: "2026-08-28-chat-verlauf-paging",
    datum: "2026-08-28",
    titel: "Ältere Nachrichten nachladen statt den ganzen Verlauf auf einmal",
    linear: "AGE-655",
    aenderungen: [
      "Ein langes Gespräch öffnet sich jetzt **sofort**, statt erst den ganzen Verlauf zu laden. Sichtbar sind die letzten 50 Nachrichten — dort, wo man weiterliest.",
      'Wer weiter zurück will, findet am oberen Rand den Knopf **„Ältere laden"**. Er holt die nächsten 50 und verschwindet, sobald der Verlauf vollständig ist.',
      "**Die Ansicht bleibt dabei stehen**, wo sie war. Nachgeladene Nachrichten treten oben hinzu, ohne dass es ans Ende des Gesprächs springt.",
      "Die Tagesmarker rücken mit: lädt man ältere Nachrichten desselben Tages nach, steht der Marker danach über der ersten davon.",
      "Gilt in der **Gesprächsansicht und im angedockten Fenster** gleichermassen.",
    ],
  },
  {
    slug: "2026-08-28-admin-setzt-stufe",
    datum: "2026-08-28",
    titel: "Ein Admin setzt die Stufe eines einzelnen Mitglieds",
    linear: "AGE-634",
    aenderungen: [
      "Eine neue `SECURITY DEFINER`-RPC `admin_set_tier(p_profile_id, p_tier, p_grund)`, die `is_admin()` im Rumpf prüft und **in beide Richtungen** setzt.",
      "Jede Änderung schreibt eine Zeile nach `public.admin_audit` — mit alter Stufe, neuer Stufe und Begründung. Ohne sie ist eine Stufe, die nicht aus Stripe stammt, später nicht erklärbar.",
      'Eine Begründung ist **Pflicht**. Eine Spur ohne Grund beantwortet „wer und wann", aber nicht „warum" — und genau das ist die Frage, die man drei Monate später stellt.',
      "Die Fläche sitzt in der Einzelbearbeitung eines Mitglieds und benennt, was Stripe später damit tut.",
      'Der Kommentar an `apply_upgrade` wird nachgezogen: „der einzige Schreibweg für den Tier" stimmt danach nicht mehr.',
    ],
  },
  {
    slug: "2026-08-27-video-freigabe-merken",
    datum: "2026-08-27",
    titel: "Video-Freigabe merken statt bei jedem Video erneut fragen",
    linear: "AGE-621",
    aenderungen: [
      "Eine Aktivierung gilt fortan **je Anbieter und dauerhaft**, gespeichert auf dem Endgerät. YouTube freizugeben lässt Vimeo unberührt.",
      'Die Freigabe greift **ohne Neuladen** auch für die übrigen Flächen derselben Seite. Sonst wäre „einmalig" auf einer Seite mit zwei Videos unwahr.',
      "Ein **frisch angeklicktes** Video spielt weiter sofort ab und bekommt den Fokus. Ein Video, das nur wegen einer **gemerkten** Freigabe geladen wird, tut beides nicht.",
      "Auf der Datenschutzseite steht ein **Widerruf**, der die Freigabe je Anbieter zurücknimmt und ohne Konto erreichbar ist.",
      "Die Rechtstexte ziehen nach. Sie behaupten heute wörtlich das Gegenteil.",
    ],
  },
  {
    slug: "2026-08-27-release-notes-an-alle",
    datum: "2026-08-27",
    titel: "Release-Notes: archivierte Changes als redigierbare Nachricht an alle Mitglieder",
    linear: "AGE-631",
    aenderungen: [
      "**Ein Admin sieht die noch nicht angekündigten Changes.** Die Liste entsteht zur **Bauzeit** aus `openspec/changes/archive/` als erzeugtes Modul und liegt damit im ausgelieferten Bündel. Kein CI-Geheimnis, kein `service_role`-Weg in die Datenbank, keine zweite Tabelle für Einträge.",
      "**Er wählt mehrere aus und bekommt einen Entwurf**, den er frei überschreibt. Der Entwurf ist ein Vorschlag, kein Ergebnis.",
      "**Eine neue Tabelle `release_notes`** hält Titel, Text, die Menge der abgedeckten Verzeichnisnamen und den Zustand `draft` / `sent`.",
      "**Eine `SECURITY DEFINER`-RPC `send_release_note(id)`** stellt zu: sie schaltet den Zustand **bedingt** um und schreibt erst dann je aktiviertem Mitglied eine `notifications`-Zeile vom Typ `release_note`. **Zweimal senden ist ausgeschlossen**, und zwar in der Datenbank, nicht im Knopf.",
      "**Ein neuer Hinweistyp `release_note`** in der Glocke, mit eigenem Renderer.",
      "**Eine Seite `/neues`**, die alle zugestellten Release-Notes zeigt. Ohne sie wäre ein weggeklickter Hinweis unauffindbar: die Glocke liest nur ungelesene und deckelt bei 50 (`hinweise.ts:31`).",
      '**Ein Menüeintrag** in der Administration — die Anforderung „Das Administrationsmenü trägt seine Flächen vollständig" gilt auch für diese.',
    ],
  },
  {
    slug: "2026-08-27-notify-contact-request-definer-rpcs",
    datum: "2026-08-27",
    titel: "notify-contact-request liest über eine DEFINER-RPC statt als service_role",
    linear: "AGE-623",
    aenderungen: [
      "**Neue `SECURITY DEFINER`-RPC** `notify_contact_request_daten(uuid, uuid, uuid)`, ausführbar allein für `service_role`. Sie liefert in einem Aufruf die Zeile aus `contact_requests`, die Zustelladresse des Empfängers und den Anzeigenamen des Gegenübers.",
      "**Die Bindung wandert in die Datenbank.** Die RPC gibt **nichts** zurück, wenn die übergebene Empfänger- und Gegenüber-Kennung nicht die beiden Beteiligten genau dieser Anfrage sind. Heute liegt diese Bindung allein in der Function; danach hält sie auch dann, wenn die Prüfung dort fiele.",
      "`notify-contact-request` ruft die RPC statt der drei `.from(...)`-Lesezugriffe. Der Abgleich Payload ⇄ Datenbank (`passtZurDatenbank`) **bleibt unverändert**, ebenso alle Antwortcodes: 502 bei Lesefehler, 409 bei Abweichung.",
      "Die Zusage in `rls_test.sql` bleibt in diesem Change **auf ihre eine Tabelle beschränkt**; sie wird nicht zum Grundsatz erhoben.",
    ],
  },
  {
    slug: "2026-08-27-glocke-und-hinweistypen",
    datum: "2026-08-27",
    titel: "Glocke verdrahten und vier Hinweistypen",
    linear: "AGE-620",
    aenderungen: [
      "Die Glocke liest die eigenen `notifications`, zeigt die Ungelesen-Zahl und markiert gelesen — einzeln und alle. Bei null zeigt sie **keine** Zahl.",
      "**Vier** neue Typen, geschrieben von Triggern auf `posts`, `events`, `comments` und `post_likes`.",
      "**Opt-out je Mitglied und je Typ** in den Einstellungen, per Default AN.",
      "Die Anforderung für die Glocke wird aus `add-lifecycle-notifications` (AGE-299) **herausgelöst**; jener Change behält den Mail-Teil.",
    ],
  },
  {
    slug: "2026-08-27-entzuege-nennen-alle-rollen",
    datum: "2026-08-27",
    titel: "Entzüge nennen alle Rollen, und der service_role-Lockdown wird gemessen",
    linear: "AGE-622",
    aenderungen: [
      "**Drei Entzüge nennen alle betroffenen Rollen** und geben danach ausdrücklich zurück, was gebraucht wird. Damit ist der Zustand von der Instanz-Sorte unabhängig. Genau diese drei, keine weiteren: `resolve_display_name`, `member_state_matches`, `staff_roles`.",
      'Der Entzug auf `staff_roles` betrifft `service_role`. Er ist **kein No-op auf PROD** — das war die Annahme des ersten Entwurfs und sie ist widerlegt (siehe unten). Er ist trotzdem **belegt gefahrlos**: `admin-change-email/index.ts:94` und `admin-set-member-ban/index.ts:36` halten beide ausdrücklich fest, dass ein direktes `.from("staff_roles")` in „permission denied" liefe — sie tun es deshalb nicht. Keine Fläche liest diese Tabelle als `service_role`.',
      '**Der `service_role`-Lockdown wurde nie ausgesprochen.** `20260715140000_explicit_grants.sql:35-36` sagt wörtlich *„service_role bleibt unangetastet: es umgeht RLS per Definition und traegt die Edge Functions"*, und der Entzug in Abschnitt 1 lautet `revoke all on all tables in schema public from anon, authenticated` — ohne `service_role`. Der Grundsatz, auf den sich `rls_test.sql:1866` beruft, gilt also nur dort zufällig, wo die Instanz von sich aus nichts vergibt. Der Kommentar dort wird entschärft, damit er nicht weiter eine Zusage behauptet, die er nicht trägt.',
      "Die Anforderung nimmt `service_role` in die Aufzählung der zu nennenden Rollen mit auf und sagt aus, dass derselbe Migrationsstand auf beiden Instanz-Sorten denselben Rechtezustand ergeben muss.",
      'Die CLI-Version in `ci.yml` wird auf eine **konkrete Nummer** gepinnt, nicht auf „die letzte neue". Nicht als Behebung, sondern damit die Umgebung nicht wieder über Nacht unter dem Repo wegwandert. Gepinnt wird auf die **neue, strengere** Sorte, damit weitere zu enge Entzüge weiterhin auffallen statt zugedeckt zu werden.',
      "**Die Gegenprobe in `grants_test.sql` wird repariert.** Sie entzog bis heute nur `from public` und behauptete damit, genau die Formulierung wirke, die AGE-602 als unzureichend beschreibt. Auf dem alten lokalen Stack ging das durch; auf der neuen Sorte fällt sie. **Eine Gegenprobe, die die falsche Form vorführt, ist schlimmer als keine — sie schreibt den Irrtum fest, den sie aufdecken soll.** Neu dazu kommt eine dritte Probe, die den rollen-eigenen Grant **selbst herstellt** und dann zeigt, dass `from public` ihn nicht mitnimmt. Die misst auf **jeder** Instanz-Sorte etwas.",
      "**Der Pin ist nicht bloß Hygiene — er ist der Biss.** Zwei der neuen Szenarien können auf dem alten lokalen Stack gar nicht rot werden: dort halten `authenticated` und `service_role` von sich aus nichts, und ein Vergleich zweier Instanz-Sorten ist innerhalb einer Instanz ohnehin nicht führbar. Diese Szenarien messen ausschließlich auf der gepinnten CI-Sorte etwas. Das Delta sagt das aus, statt es implizit zu lassen — eine Zusage, die überall grün ist, hat sonst niemand als solche erkannt.",
    ],
  },
  {
    slug: "2026-08-27-chatfenster-angedockt",
    datum: "2026-08-27",
    titel: "Angedockte Chatfenster unten: mehrere Gespräche gleichzeitig, minimierbar",
    linear: "AGE-639",
    aenderungen: [
      "**Ein Klick in der stehenden Leiste öffnet ein Fenster** statt zu navigieren — ab `xl`, also genau dort, wo die Leiste angedockt steht. Darunter (Schublade, Telefon) bleibt es beim heutigen Weg: die Adresse.",
      "**Höchstens drei Fenster**, unten rechts aufgereiht, **zwischen beiden Leisten**. Jedes bis zu 18 rem breit; wird es eng, teilen sich alle drei den Platz, statt dass eines angeschnitten wird. Ein viertes Gespräch schliesst das am längsten unberührte — es ist damit nicht verloren, sondern steht unverändert in der Leiste daneben.",
      "**Jedes Fenster minimiert und schliesst einzeln.** Minimiert bleibt seine Titelzeile stehen: Avatar, Name, Ungelesen-Zähler, beide Schalter.",
      "**Die Fenster überleben den Seitenwechsel und das Neuladen.** Offene Threads und ihr Minimiert-Zustand liegen gerätelokal, wie `fbc.sidebarCollapsed` und `fbc.chatCollapsed` es schon tun.",
      "**Ein aufgezogenes Fenster rückt den Lesestand vor**, genau wie die Vollansicht. Ein minimiertes nicht — es ist nicht gelesen worden.",
      "**Ein Realtime-Kanal, nicht N.** Das bestehende `subscribeToAllMessages`-Abo in der Hülle bedient die Fenster mit; kein Fenster öffnet einen eigenen Kanal.",
      "**`/chat` und `/chat/:threadId` bleiben unverändert** — Vollansicht, Deep-Link, und der einzige Weg unterhalb von `xl`. Auf diesen Routen steht die Fensterreihe nicht, aus demselben Grund, aus dem die Leiste dort nicht steht.",
      "**Die Toasts weichen der Fensterreihe nach oben aus**, über dieselbe geteilte CSS-Variable, mit der der Rahmen schon heute seine Leistenbreite verteilt.",
    ],
  },
  {
    slug: "2026-08-27-chat-rechte-sidebar",
    datum: "2026-08-27",
    titel: "Der Chat wird eine zweite angedockte Leiste an der rechten Viewport-Kante",
    linear: "AGE-627",
    aenderungen: [
      "`message_threads` bekommt `last_message_at`, `last_message_body` und `last_message_sender_id`, gepflegt von einem `security definer`-Trigger auf `messages`. Damit wird die Liste **eine** begrenzte, serverseitig sortierte Abfrage; `messages` wird für die Liste gar nicht mehr gelesen. Begründung, verworfene Alternative und der Nachweis, dass das **keine** Lesebestätigung ist: `design.md`.",
      "`fetchThreads` bekommt Seitenparameter, und `threadsQueryKey` bekommt sie auch — sonst teilen Panel und `/chat` einen Cache-Eintrag.",
      '**`/chat` lädt künftig ebenfalls eine Seite.** Es gibt eine Datenquelle mit einem Umfang; beide Flächen zeigen denselben. (Die erste Fassung behauptete, `/chat` bleibe unverändert — das war mit „dieselben Threads" und „begrenzte Seite" zusammen nicht erfüllbar.)',
      "Eine **zweite angedockte Leiste an der rechten Viewport-Kante**, gebaut nach denselben Regeln wie die linke: volle Höhe, bündig am Rand, Trennlinie statt Schatten. Sie trägt die Unterhaltungsliste.",
      "**Nur für angemeldete Mitglieder.** Die Hülle rendert auch ausgeloggt (`AppShell.tsx:578–587`); ein Rail mit Sprechblase für einen Gast wäre ein Versprechen ins Leere.",
      "**Beim ersten Besuch eingeklappt**, mit eigenem Speicherschlüssel neben dem der linken Leiste.",
      "Unterhalb `lg` ein **Off-Canvas-Drawer von rechts** mit **eigenem Öffner** in der Topbar, gespiegelt zum Hamburger (`AppShell.tsx:513–520`). Höchstens ein Drawer ist offen.",
      "**Auf `/chat` und `/chat/:threadId` blendet das Panel aus** — dort stünde die Liste sonst zweimal auf einem Schirm.",
      "`/chat` bleibt als Route bestehen. Unterhalb `lg` und aus einer E-Mail heraus ist die Vollseite weiterhin der Weg.",
    ],
  },
  {
    slug: "2026-08-26-redesign-guest-surfaces",
    datum: "2026-08-26",
    titel: "Die zwei Gaesteflaechen gestalten und von erfundenen Angaben befreien",
    linear: "AGE-616",
    aenderungen: [
      '`HomePage.tsx:81` — `<Kpi value="120+" label="Mitglieder" />`, waehrend die Datenbank rund 70 Profile haelt',
      '`HomePage.tsx:82` — `<Kpi value="24" label="Events 2026" />`, nicht aus `events` berechnet',
      'zwei `<Testimonial>` mit erfundenen Zitaten, zugeschrieben an „Ein Impact-Mitglied" und „Ein Focus-Mitglied"',
    ],
  },
  {
    slug: "2026-08-26-password-reset-flow",
    datum: "2026-08-26",
    titel: "password-reset-flow",
    linear: "AGE-505",
    aenderungen: [
      "**Der vorhandene Token-Weg wird geöffnet, nicht dupliziert.** Das Einlösen — Beanspruchen in einer Anweisung, Passwort setzen, Sitzungen widerrufen — ist gebaut, geprüft und wird unverändert wiederverwendet.",
      "`issue_activation_token` gibt für ein aktiviertes Konto ein Token aus, Status **`issued_reset`**, statt mit `already_activated` abzulehnen. Der Zweig wandert dabei **hinter** 60-s-Sperre, Schutzfenster und Tageskontingent — stünde er wie heute davor, ginge der Reset-Weg an allen drei Grenzen vorbei.",
      "**BREAKING (intern):** `already_activated` verschwindet als Status von `issue_activation_token`. Einziger Aufrufer ist `send-activation`. `request_own_activation_token` behält den Status und bleibt unangetastet.",
      '`send-activation` wählt an `issued_reset` einen **zweiten Mailtext**: 72 Stunden, „alle Geräte werden abgemeldet", und „falls du das nicht warst, ignoriere diese Mail". Sein Link zeigt auf `/passwort-neu`.',
      'Zwei Routen: `/passwort-vergessen` (anfordern) und `/passwort-neu` (einlösen), erreichbar über „Passwort vergessen?" auf `/login`. Das Einlöse-Bauteil ist dasselbe wie für die Aktivierung, unterschieden nur durch die Wortwahl.',
    ],
  },
  {
    slug: "2026-08-26-nachrichten-ungelesen-zaehler",
    datum: "2026-08-26",
    titel: "Nachrichten sichtbar machen: Zugang und Ungelesen-Zähler",
    linear: "AGE-583",
    aenderungen: [],
  },
  {
    slug: "2026-08-26-fix-mobile-overflow",
    datum: "2026-08-26",
    titel: "Kein seitliches Schieben auf schmalen Geraeten",
    linear: "AGE-584",
    aenderungen: [
      '**Eine Mindestbreite festschreiben: 320 px.** Darunter wird nicht unterstuetzt. Ohne diese Zahl ist „laeuft ueber" keine pruefbare Aussage.',
      "**Die gemessenen Stellen reparieren** — `min-w-0` auf die Grid-Kinder, die kuerzenden Text tragen; die zwei festen Spaltensaetze hinter einen Breakpoint, darunter gestapelt.",
      "**Die Admin-Tabelle** bekommt einen scrollbaren Rahmen, damit sie auf dem Telefon bedienbar bleibt, statt die Seite zu schieben.",
      "**Den Defekt wegkonstruieren:** `min-w-0` in die zwei geteilten Bausteine, durch die beide gemessenen Faelle laufen — `Card` und `StaggerItem`.",
      "**Ein schmaler Waechter** im Testlauf verbietet feste Rasterspalten ohne Breakpoint. Er laeuft in `pnpm test` und damit in CI mit.",
    ],
  },
  {
    slug: "2026-08-26-finish-ui-polish",
    datum: "2026-08-26",
    titel: "Tiered name resolution, logout isolation, and UI polish",
    linear: "AGE-291",
    aenderungen: [
      "Resolve display names through a **single shared resolver** keyed off the caller's status: full name for self and for any **activated** member; the masked \"Mitglied\" label for everyone else (in practice: anonymous visitors). Applied in the DB read path across **every** name-bearing surface (directory, feed, events, matching, profiles), so masking can't be bypassed via another surface.",
      "**Clear** (not just invalidate) the client query cache on logout / principal change (AGE-258) — specified as a data-isolation invariant.",
      '(Client-only, no spec delta) Inline "Mein Bereich" accordion (AGE-292) and menu label cleanup (AGE-293).',
    ],
  },
  {
    slug: "2026-08-26-anon-grants-und-feed-sichtbarkeit",
    datum: "2026-08-26",
    titel: "anon-grants-und-feed-sichtbarkeit",
    linear: null,
    aenderungen: [
      "Eine Migration entzieht `execute` für die fünf Funktionen `from public, anon` — `anon` **namentlich**, so wie `admin_list_members` es schon richtig macht. Das macht das Ergebnis unabhängig davon, was die Default Privileges der jeweiligen Instanz gewähren.",
      'Die falsche Zusage in `directory-search` wird korrigiert. Ihre Begründung („kein Recht wurde auf die neue Signatur vererbt") ist **nachweislich falsch** — genau das ist passiert. Die neue Fassung sichert den **Rechte-Zustand** zu, nicht das Ergebnis eines Aufrufs.',
      "Die pgTAP-Zusage prüft ab jetzt das **Privilegien-Bit** (`has_function_privilege('anon', …, 'execute')`) statt einer Fehlermeldung, und bringt eine **Gegenprobe** mit: sie erteilt das Recht im Test, misst `true`, entzieht es, misst `false`. Ohne die Gegenprobe wäre auch die neue Zusage vakuum-grün — lokal hält `anon` das Recht ohnehin nicht.",
      "**Der lokale Test kann PROD-Abweichung prinzipiell nicht sehen.** Das wird in der Anforderung ausgesprochen statt kaschiert; der Beleg für PROD ist eine Katalog-Messung nach `migrate-prod`, die in `tasks.md` mit Zahlen landet.",
      "Der Zweig `visibility = 'members' and has_level(4)` wird zu `visibility = 'members'`. `is_activated()` steht in jedem dieser Prädikate bereits davor und bleibt die Hürde.",
      "Das Prädikat liegt an **vier** Stellen, am PROD-Katalog abgezählt (nicht aus den Migrationen geschätzt): Policy `posts_select_by_visibility` sowie die Funktionen `post_engagement_counts`, `post_media_lesbar` und `former_member_entries`. Alle vier ändern sich **in einer Migration**; drei davon zu ändern und eine zu vergessen ergäbe einen Feed, dessen Zähler oder Bilder nicht zu seinen Zeilen passen.",
      "`feed_tag_counts` und `feed_top_authors` sind `security invoker` und tragen **keine** Abschrift — sie ändern sich mit, ohne angefasst zu werden. Das ist die Probe aufs Exempel für die Regel in `community-feed`, dass Abschriften zu vermeiden sind.",
      "Die übrigen `has_level(4)`-Vorkommen bleiben **unangetastet**: die Kontaktanfrage-Schwelle und die Event-Teilnahme sind eigene Entscheidungen und nicht Gegenstand von AGE-601.",
    ],
  },
  {
    slug: "2026-08-26-admin-und-profilflaechen",
    datum: "2026-08-26",
    titel: "admin-und-profilflaechen",
    linear: null,
    aenderungen: [
      "Neue Route `/admin/feedback` hinter `RequireAdmin`, neuer Eintrag im Administrationsmenü (heute genau zwei Einträge, hart in `AppShell.tsx`).",
      "**BREAKING (intern):** `admin_list_feedback()` bekommt `p_limit`/`p_offset` und gibt zusätzlich `profile_id` heraus. Der Rückgabetyp ändert sich, also `drop` + `create` — `create or replace` kann das nicht. Sieben Zusagen in `rls_test.sql` hängen an der alten, argumentlosen Signatur und werden mitgezogen.",
      "Die Karte auf `/admin` **entfällt ersatzlos**. Zwei Flächen auf denselben Daten driften, sobald eine davon Paging bekommt — und genau das passiert hier.",
      "`profile_id` wird herausgegeben, obwohl sie heute keinen Aufrufer hat: der Chat braucht sie, und die Funktion wird für das Paging ohnehin neu angelegt. Sie später nachzureichen kostete eine zweite Migration für dieselbe Zeile.",
      "Eine **neue, eigene** RPC liefert die Zahlen. `admin_list_members` wird **nicht** angefasst: fünf Zusagen casten auf ihre exakte Signatur (`::regprocedure`, ein Fehler statt eines Fails), und eine weitere ist ausdrücklich als Wächter gegen zusätzliche Spalten gebaut.",
      '„Alle" und „Mitgliedschaft" teilen denselben Mengenzweig und tragen deshalb dieselbe Zahl. Das ist richtig, nicht doppelt.',
      "Jede Zeile springt zu **ihrem** Beitrag im Feed, nicht in die Liste. Dafür entsteht ein Deeplink, den es heute nicht gibt: weder Route noch Parameter noch Anker.",
      "Ein Beitrag ohne Text zeigt einen Ersatztext statt einer leeren Zeile — an **beiden** Karten, denn `/p/:id` und `/profil` haben denselben Fehler.",
    ],
  },
  {
    slug: "2026-08-26-add-video-consent-gate",
    datum: "2026-08-26",
    titel: "Video-Player erst auf Anforderung laden",
    linear: "AGE-611",
    aenderungen: [],
  },
  {
    slug: "2026-08-26-add-legal-pages",
    datum: "2026-08-26",
    titel: "Rechtsseiten als temporaere Fassung, verlinkt im Footer",
    linear: "AGE-497",
    aenderungen: [
      "**Vier Routen** — `/impressum`, `/datenschutz`, `/agb`, `/cookies` — mit den Texten aus den Anwaltsdokumenten.",
      "**Ausserhalb der `AppShell`**, wie `/login`. Begruendung unten.",
      "**Ein Footer** in der `AppShell` mit den vier Links, dezent, in beiden Themes.",
      "**Ein Entwurfshinweis** auf jeder Seite, der benennt, **was an dieser Seite noch nicht final ist** — pro Seite verschieden, nicht ein Einheitssatz.",
      "**Ein Inhaltsmodell ohne neue Abhaengigkeit.** Kein Markdown-Renderer, kein `dangerouslySetInnerHTML`.",
    ],
  },
  {
    slug: "2026-08-26-add-easybill-invoicing",
    datum: "2026-08-26",
    titel: "Add EasyBill invoicing and proration",
    linear: null,
    aenderungen: [
      "Generate a §14 UStG-compliant EasyBill invoice (FBC is USt-pflichtig) for every completed upgrade payment, idempotent per Stripe payment id.",
      "Prorate mid-cycle upgrades via **Stripe-native** subscription proration (`proration_behavior`); FBC does not compute proration itself.",
      "Retire the existing `billing-upgrades` requirement that declared invoicing/proration out of scope (removed in the spec delta).",
      "Refunds / disputes / credit notes (Stornorechnung) are **explicitly out of scope** — named follow-up.",
    ],
  },
  {
    slug: "2026-08-26-add-admin-member-lifecycle",
    datum: "2026-08-26",
    titel: "add-admin-member-lifecycle",
    linear: "AGE-581",
    aenderungen: [
      "**Ein Menü je Zeile** statt loser Knöpfe. Es trägt die bestehenden Handlungen und die neuen; die Zeile bleibt lesbar, wenn eine sechste dazukommt.",
      "**Deaktivieren** — zwei Sperren, nicht eine. `banned_until` in `auth.users` über eine Edge Function mit `service_role`, damit die Anmeldung schon bei GoTrue scheitert und gar keine Sitzung entsteht; und `disabled_at` in `profiles`, damit das DB-Gate greift, falls eine Sitzung noch läuft. Umkehrbar, beide Richtungen protokolliert.",
      "**Eine Rolle überlebt den Entzug des Zugangs nicht.** `is_admin()` und `is_matching_manager()` lesen heute nur `staff_roles` — ein deaktivierter Admin behielte jede Fähigkeit. Beide bekommen die Zugangsbedingung.",
      '**Löschen, weich** — `deleted_at` wird gesetzt, die Zeile bleibt. Gelöschte sind nirgends gelistet ausser im Tab „Gelöscht" und von dort wiederherstellbar. Ein Hard-Delete entsteht in diesem Change **nicht**.',
      '**Was ein entferntes Mitglied hinterlassen hat, bleibt stehen.** Beiträge und Kommentare bleiben lesbar; der Autor erscheint als „Ehemaliges Mitglied" ohne Verweis auf ein Profil, das es nicht mehr gibt. Ein Beitrag, der aus einem Gesprächsfaden verschwindet, in dem andere geantwortet haben, reisst ein Loch in fremde Beiträge.',
      '**Tabs statt eines Status-Auswahlfelds**: Alle · Nicht aktiviert · Deaktiviert · Gelöscht · Mitgliedschaft. Deaktivierte und Gelöschte erscheinen **nur** hinter ihrem eigenen Tab, nicht unter „Alle".',
      '**Der Tab „Mitgliedschaft"** zeigt je Mitglied Stufe, bezahlt-bis und **Zahlungsart** (neu) und lässt die letzten beiden in der Zeile ändern — die **Stufe bleibt hier nur lesbar**, ihr Wechsel hat einen eigenen Weg (AGE-516). Die Alternative wäre, Detlevs Liste sechzigmal über die Einzelansicht einzupflegen.',
      "**`payment_type` als neues Feld** in `profile_legacy`, mit den acht Werten aus dem Bestand: `rechnung`, `stripe`, `copecart`, `paypal`, `digistore24`, `ehren`, `partner`, `offen`.",
    ],
  },
  {
    slug: "2026-08-26-add-academy-content",
    datum: "2026-08-26",
    titel: "Add data-driven Academy content, enrollment and tier-gated access",
    linear: "AGE-262",
    aenderungen: [
      "Replace the hard-coded lesson stub with a real content model of courses, lessons and downloadable resources (each with a `published` state), seeded via migration.",
      'Let a member enroll and track per-lesson completion; "My Courses" surfaces the next incomplete lesson (resume) and marks a course complete when all lessons are.',
      "**Enrollment is the tier gate**: enrolling requires clearing `courses.min_tier` (int rank, `has_level`); course cards stay visible to all for upsell, lessons and resources are readable only once enrolled, and access persists after a later downgrade.",
    ],
  },
  {
    slug: "2026-08-25-verzeichnis-reiter-und-kartencover",
    datum: "2026-08-25",
    titel: "Verzeichnis: zwei Reiter, Cover auf der Karte, Kompass-Chips raus",
    linear: "AGE-595",
    aenderungen: [
      '`/mitglieder` bekommt zwei dauerhaft sichtbare Reiter mit Zählern: „Alle Mitglieder" und „Meine Kontakte".',
      "Die Karte verliert die Kompass-Marken und gewinnt das Cover. Die Branche bleibt.",
      "`search_directory` liefert `cover_url` mit.",
    ],
  },
  {
    slug: "2026-08-25-titelbilder-einpassen",
    datum: "2026-08-25",
    titel: "Titelbild-Felder auf das Verhältnis bringen, auf das zugeschnitten wird",
    linear: "AGE-596",
    aenderungen: [
      "Die drei Bildfelder werden **3:1**.",
      "Der Profilkopf verliert seinen Höhendeckel.",
      "Das Bild wird eingepasst statt beschnitten, damit die Abweichler unter 3:1 Ränder bekommen statt Verluste.",
      "Der Platzhalter-Verlauf rückt **unter** das Bild, damit die Ränder nicht als flache Fläche erscheinen.",
    ],
  },
  {
    slug: "2026-08-25-stille-fehlschlaege-und-anfragen-weg",
    datum: "2026-08-25",
    titel:
      "Stille Fehlschläge sichtbar machen, und der Weg zu eingehenden Anfragen (AGE-591/592/593)",
    linear: null,
    aenderungen: [
      '**Der Weg zu eingehenden Anfragen (AGE-592).** „Meine Anfragen" steht heute ausschließlich auf `/kontakte`, und dieser Routeneintrag trägt `section: "sub"` — `SIDEBAR_SECTIONS` rendert nur `entdecken` und `mein-bereich`, es gibt also **keinen Menüeintrag**. Ein Eintrag **„Meine Anfragen"** erscheint unter „Mein Bereich", **solange** offene Anfragen vorliegen, mit ihrer Anzahl.',
      '**Registrierung auf eine bekannte Adresse (AGE-591).** Beim Bauen gemessen und dabei korrigiert: GoTrue antwortet **je nach Einstellung verschieden**. Mit eingeschalteter E-Mail-Bestätigung mit 200 ohne Fehler und ohne Sitzung (Aufzählungsschutz) — so stand PROD vom 16. bis 25.08., daher die stumme Seite. Seit `mailer_autoconfirm` wieder `true` ist, mit **HTTP 422 `user_already_exists`**, und das Formular zeigte dessen rohen englischen Text „User already registered" — der nirgendwohin führt und die Existenz des Kontos ausspricht. **Beide** Ausgänge bekommen jetzt denselben neutralen Hinweis, der zum **Zugangslink** führt. Jeder andere Fehler bleibt im Klartext.',
      '**Die Nebenwirkungen der Registrierung hängen am falschen Zweig.** In `AuthProvider.signUp` laufen `logEvent("signup")` und das sitzungsgebundene `resendActivationLink()` unter `if (!error)` — also **auch** bei einer Wiederholung ohne Sitzung. Das ist die `42501`-Anfrage aus den PROD-Logs und eine Registrierungszählung, die Wiederholungen mitzählt. Beides zieht hinter `data.session`. **Dieser Punkt kam erst aus dem Plan-Review** und ist ein echter Fehler, kein Textproblem.',
      '**Anfragen-Widget bei Fehler (AGE-593).** `isError` steht in derselben Bedingung wie „nichts da"; ein gescheiterter Abruf ist von einem leeren Posteingang nicht zu unterscheiden. `isError` wird getrennt — aber nur dort, wo **keine** Daten vorliegen; ein gescheitertes Nachladen über vorhandenen Anfragen darf sie nicht verstecken.',
    ],
  },
  {
    slug: "2026-08-25-profil-biete-suche-und-radar",
    datum: "2026-08-25",
    titel: "Profilseite: Kompass-Einträge entdoppeln, Erfolgsradar entfernen",
    linear: "AGE-597",
    aenderungen: [
      "Kategorisierte Einträge werden zu einer Marken-Reihe, ohne rohen Schlüssel und ohne redundanten Titel.",
      "Freitext-Einträge werden Text; der Titel entfällt, wo er nur der Anfang der Beschreibung ist.",
      "Führende `'-`-Artefakte werden **beim Darstellen** entfernt, nicht in der Datenbank.",
      "Nachgemessen am 25.08. (`scripts/probe-age597-kompass-bestand.ts`): der Import kürzt lange Titel an der Wortgrenze mit einem Auslassungszeichen, nicht mitten im Wort, und **kein** Editor-Titel im Bestand ist eigenständig.",
      "Der Erfolgsradar verschwindet aus der öffentlichen Profilansicht.",
    ],
  },
  {
    slug: "2026-08-25-feed-beitragstyp-mehrfachauswahl",
    datum: "2026-08-25",
    titel: "Beitragstyp mehrfach wählbar (AGE-590)",
    linear: null,
    aenderungen: [
      '**BREAKING (intern):** `FeedAuswahl.typ: FeedTyp | null` wird zu `FeedAuswahl.typen: FeedTyp[]`. Der `null`-Zustand entfällt **ersatzlos** — die leere Menge heißt „alle Typen", genau wie die leere Tagmenge heute „alle Beiträge" heißt (`fetchFeed`: `if (gewaehlteTags.length > 0)`).',
      "Die vier voneinander unabhängigen `if`-Bedingungen in `fetchFeed` werden zu **einer** ODER-Verknüpfung über die gewählten Typen.",
      "`feedSeitenKey` trägt die **kanonisierte** Typmenge (ohne Dubletten, sortiert) statt eines einzelnen Wertes — nach demselben Muster wie `normalisierteTags` und aus demselben Grund: ein Klick, der nur die Reihenfolge dreht, darf dieselbe Auswahl nicht ein zweites Mal laden.",
      'Die Seitenleiste zeigt statt des `<Select>` vier Auswahlkästchen. Der Eintrag „Alle Typen" entfällt als eigene Option — „alle" ist der Zustand ohne Haken.',
      "Die Filterleiste über dem Feed (heute ein Chip mit dem einen Typ) zeigt einen Chip **je gewähltem Typ**, jeder einzeln abwählbar, wie bei den Tags.",
    ],
  },
  {
    slug: "2026-08-25-event-anmeldeknopf-teilnahmeschwelle",
    datum: "2026-08-25",
    titel: "Der Anmeldeknopf hält sich an die Teilnahmeschwelle (AGE-594)",
    linear: null,
    aenderungen: [
      "Der Knopf ist gesperrt, wenn die Stufe des Betrachters die Schwelle des Events nicht erreicht. **Daneben** steht der Grund samt der nötigen Stufe und ein Weg zur Mitgliedschaft — ein grauer Knopf ohne Erklärung wäre seinerseits eine Fläche, die nichts sagt.",
      "Gespiegelt wird die Funktion **vollständig**, einschließlich ihrer Ausnahmen: `public` steht jedem offen, und der **Host** darf zu seinem eigenen `members`-Event unabhängig von seiner Stufe.",
    ],
  },
  {
    slug: "2026-08-25-activity-concept-level",
    datum: "2026-08-25",
    titel: "activity-concept-level",
    linear: null,
    aenderungen: [
      "**Ein Icon-Satz** — alle **wiederverwendbaren Glyphen** in einem Stil an einer Stelle. Markenmarke, Kompassmarke, Avatar-Platzhalter und Diagramm-Vektoren bleiben ausgenommen: SVGs liegen in **14** Dateien außerhalb `src/vision`, und ein 48er-Logo oder ein 200×48-Diagramm kann den 24er-Glyphstil nicht treffen. Für die Markenmarke besteht eine eigene Anforderung. Heute liegen neben `NavIcon.tsx` (elf Pfad-gekeyte Menü-Icons plus elf gefüllte Fassungen) **neun** Einzel-SVGs in den vier vom Issue genannten Dateien, nicht sieben: `AppShell.tsx` allein trägt vier (`ChevronLeftIcon`, `BellIcon`, `MenuIcon`, `ChevronDownIcon`), dazu `FeedbackIcon`, `SearchIcon` und im Feed `HeartIcon`, `CalendarIcon`, `CommentIcon`. Ungenannt im Issue, aber im selben Befund: **`CrownIcon` steht zweimal byte-gleich im Baum** (`mein-bereich/building-blocks.tsx` und `profile/ProfileHero.tsx`), und `matching/CategoryIcon.tsx` ist ein **zweiter vollständiger Satz** mit eigenem `Record`.",
      "**Ein Bereichs-Kanon** — die Zuordnung `Bereich → Icon + Farbe` als eine Modulkonstante. Er trägt nur Gegenstandsbereiche (Events, Mitglieder, Nachrichten, Aktivität/Beiträge, Kontakte, Kompass, Highlights). Chevron, Menü, Glocke und Lupe sind **Bedien**-Symbole ohne Bereich und ohne Bereichsfarbe; sie gehören in den Satz, nicht in den Kanon. Ein Kanon, der sie mitträgt, müsste ihnen eine Farbe erfinden.",
      "Der Composer wandert in die linke Spalte. Heute rendert `CommunityFeed.tsx:156` ihn **vor** dem Raster, deshalb liegt er über Feed und Sidebar; die Sidebar beginnt dadurch tiefer als der Feed.",
      'Die Medientyp-Zeile bekommt Icons aus dem Kanon. **Bild und Video-Link gibt es bereits** — der Screenshot zeigt den Composer zugeklappt, der Abstand ist kleiner, als das Bild vermuten lässt. Neu ist hier nur die Beschriftung mit Symbolen; „Event" und „Umfrage" bleiben diesem Change fern (Event ist systemverwaltet, Umfrage ist Change B).',
      '**Drei Reiter**: „Alle Beiträge", „Beiträge von mir", „Gespeichert". `fetchFeed({ autorId })` trägt den mittleren bereits.',
      '**Sortierung mit Umschalter**, einschließlich „Beliebteste" — siehe unten, das ist der teuerste Teil dieses Changes.',
      "Beide Aggregate laufen **unter der RLS des Aufrufers** (`security invoker`) und kopieren das Sichtbarkeitsprädikat ausdrücklich **nicht**. Eine Zahl über Beiträge, die der Betrachter nicht sehen darf, verrät genau diese Beiträge — und unter `invoker` stimmt sie, weil die Regel wirkt, statt weil eine Abschrift sie nachspricht. Das Repo führt das Prädikat bereits an drei Stellen; eine vierte und fünfte Kopie wären Aufwand für ein Ergebnis, das ohne sie schon richtig ist.",
      "Gezählt wird über die **aktiven kuratierten Tags** aus `public.tags`, nicht über `unnest(posts.hashtags)` — sonst erschienen freie und stillgelegte Schlagworte.",
      '„Aktivste Mitglieder" zeigt **fünf** Namen, gezählt nach **Beiträgen**, und es gilt `profiles_public`: kein zurückgezogenes, unbestätigtes, deaktiviertes oder gelöschtes Profil.',
      '**Auswahlkästchen sind nicht Optik.** Sie versprechen Mehrfachauswahl. Der Filter ist heute `.contains("hashtags", [tag])` — das ist **UND** und liefert bei zwei Haken fast immer nichts. Entschieden (Donald, 24.08.): **ODER**, also `.overlaps()`.',
      "Beitragstyp: Video gibt es (`nurVideos`), Event über `posts.kind`, **Bild** braucht eine Abfrage über `post_media`.",
      "Heute verschwindet die ganze Spalte bei null Tags (`TagFilter` gibt `null` zurück). Die gefüllte Sidebar SHALL das nicht erben.",
    ],
  },
  {
    slug: "2026-08-22-add-wordpress-member-import",
    datum: "2026-08-22",
    titel: "Mitglieder-Import aus WordPress (AGE-534, C10)",
    linear: null,
    aenderungen: [
      "**Neu: ein Import-Script** unter `supabase/seed/`, in der Bauweise des Demo-Seeds (`tsx`, `pg`-Direktverbindung, Infisical). Es liest den CSV-Export, bildet die Felder ab, lädt die Bilder und schreibt Konten, Profile und `profile_legacy`.",
      "**Trockenlauf ist der Standard.** Geschrieben wird nur mit einem ausdrücklichen Schalter. Ein Aufruf ohne Argumente kann nichts kaputt machen.",
      "**Neu: die fehlenden Feld-Parser** für Beitrittsdatum und Telefonnummer, plus eine Übertragung der beiden bereits gegen die echten Daten gemessenen Parser (PHP-Array, Ort/PLZ) von Python nach TypeScript. Entgegen der Annahme im Issue liegen **nur zwei der vier** Parser vor.",
      "**Neu: ein Bericht** am Ende jedes Laufs — angelegt / aktualisiert / übersprungen / fehlerhaft, je mit Grund, plus die Fälle, die Handarbeit brauchen.",
      "**Idempotenz über `legacy_source_id`.** Ein zweiter Lauf aktualisiert, statt zu duplizieren.",
      "**Die Personendaten bleiben außerhalb des Repositoriums.** Der CSV-Export trägt Klarnamen, Anschriften, Telefonnummern und Passwort-Hashes von 70 Menschen; das Repository ist öffentlich. Das Script bekommt den Pfad übergeben und **lehnt einen Pfad im Arbeitsbaum ab**; die Standardausgabe führt keine Personendaten.",
      "**Die Passwort-Hashes des Altsystems werden nicht übernommen.** Sie werden weder gelesen noch geschrieben noch protokolliert; importierte Konten entstehen ohne Passwort. Das ist der Grund, warum der ursprüngliche Plan mit einem geteilten Passwort in einer Rundmail verworfen wurde.",
      "**Der Import verschickt keine Mail.** Der Zugang entsteht dadurch, dass ein Mitglied seine Adresse auf der Plattform eingibt und den Versand selbst auslöst. Ein Versand aus dem Import heraus verschickte Links vor der Ankündigung und entwertete sie beim nächsten Lauf wieder.",
    ],
  },
  {
    slug: "2026-08-22-add-admin-member-list",
    datum: "2026-08-22",
    titel: "add-admin-member-list",
    linear: "AGE-566",
    aenderungen: [
      "**Neue Funktion `admin_list_members(p_query, p_status, p_limit, p_offset)`** — `security definer`, `search_path = ''`, `is_admin()` als erste Anweisung, alle vier Parameter mit Vorgabewert. Liefert die Verzeichnisspalten von `search_directory` plus `login_email`, `bestaetigt` und `member_since`. Unbestätigte Profile **sind** enthalten.",
      "**Neue Funktion `admin_activate_member(target uuid)`** — admin-gesicherte Hülle **neben** `mark_activated`, die in **derselben Transaktion** nach `public.admin_audit` schreibt. Die vorhandene Funktion bleibt unangetastet: sie ist für die Edge Function mit `service_role` gebaut und prüft `is_admin()` bewusst nicht.",
      '**Neue Route `/admin/mitglieder`** mit drei oben umschaltbaren Sichten — Tabelle, Admin-Karten, Verzeichnis-Ansicht — und zwei Handlungen je Eintrag: „Zugangslink schicken" und „direkt aktivieren", letzteres hinter einer namentlichen Rückfrage, weil es durch die Anwendung nicht umkehrbar ist.',
      "**`MemberCard` wird exportiert und bekommt ihr Ziel als Prop.** Sie ist heute privat und verdrahtet `/p/:id` fest; ohne diesen Schritt ist die Verzeichnis-Ansicht ein Nachbau statt einer Wiederverwendung.",
      '**Kein admin-gesetztes Passwort.** „Zugangslink schicken" ruft die vorhandene Kette `send-activation` → `issue_activation_token`; das Mitglied setzt selbst.',
      "**Keine Kontaktdaten in der Liste.** `login_email` ja, `profile_contacts` nein.",
      "**`add-admin-console` wird entflochten** (siehe Impact): es entfernt heute dieselbe Anforderung und spezifiziert dieselbe Liste ein zweites Mal.",
    ],
  },
  {
    slug: "2026-08-21-fix-frontend-routing-zwei-werte",
    datum: "2026-08-21",
    titel: "fix-frontend-routing-zwei-werte",
    linear: "AGE-579",
    aenderungen: [
      '**Die Anforderung „Zwei getrennte Supabase-Projekte mit festen Rollen" nennt zwei Werte statt drei** und streicht `SUPABASE_DB_PASSWORD` aus der Aufzählung.',
      '**Die Anforderung „Bis zum Import trägt allein DEV die Rolle beider Umgebungen" zieht nach.** Ihr Szenario „Das Aufsetzen von PROD lenkt keinen Verkehr um" nennt die drei Werte ein zweites Mal. Ohne sie widerspräche der gefaltete Hauptspec sich weiterhin selbst.',
      "**Beide betroffenen Szenarien behalten ihre Titel.** Ein umgetaufter Titel in einem MODIFIED-Block löscht das alte Szenario beim Archivieren.",
      "**Ein neues Szenario macht die Streichung prüfbar**, und zwar am Bundle statt an der Absicht: Build mit gesetztem `SUPABASE_DB_PASSWORD`, danach im Erzeugnis danach suchen.",
      '**Eine Zeile im Runbook wird mitkorrigiert** (`docs/supabase-environments.md`, „Umzug der drei prod-Werte"). Siehe unten — sie widerspricht der eigenen Anleitung 26 Zeilen darüber.',
      "**Kein Anwendungscode, keine Migration, keine Konfiguration.** Der Spec beschreibt ab hier, was ohnehin schon der Fall ist.",
    ],
  },
  {
    slug: "2026-08-21-bild-urls-relative-pfade",
    datum: "2026-08-21",
    titel: "bild-urls-relative-pfade",
    linear: "AGE-580",
    aenderungen: [
      "**Zwei Erzeuger schreiben künftig Pfade statt URLs:** `src/lib/profile.ts` (`uploadBild`, heute `getPublicUrl`) und der WordPress-Import (`supabase/seed/wp_bilder.ts:466`, der die URL von Hand zusammensetzt). Ein **dritter** Erzeuger bleibt bewusst wie er ist: der Demo-Seed schreibt `https://i.pravatar.cc/…` (`demo_personas.sql:88`, `demo_legacy_profile.sql:60`) — das ist gar kein Supabase-Storage, und die Anforderung ist deshalb auf Supabase-verwaltete Bilder begrenzt.",
      "**Ein Auflöser beim Anzeigen.** Er reicht durch, was **schon absolut** ist, und ergänzt nur nackte Pfade. Das ist keine Vorsichtsmaßnahme für einen hypothetischen Fall, sondern für zwei reale — siehe unten.",
      "**Drei Anzeigestellen**, nicht neunzehn: `<Avatar>` (der einzige Trichter für Profilbilder), `ProfileHero` (Hintergrundbild) und die Cover-Vorschau im Editor (`ProfilPage`), die den gespeicherten Wert an `ProfileHero` vorbei selbst rendert.",
      "**Eine Migration** schneidet die Bestandszeilen auf Pfade zurück — ohne die Projektkennung hart zu schreiben.",
      '**Spec:** `member-profiles` sagt heute „ein nicht aktiviertes Konto SHALL keine Bild-**URL** erhalten". Die Aussage muss auf den Pfad gezogen werden, sonst beschreibt sie eine Spalte, die es so nicht mehr gibt.',
    ],
  },
  {
    slug: "2026-08-20-sync-dev-from-prod",
    datum: "2026-08-20",
    titel: "sync-dev-from-prod",
    linear: "AGE-576",
    aenderungen: [
      "**Ein wiederholbarer Befehl `pnpm sync:dev`** ersetzt den Datenbestand von DEV durch eine Kopie von PROD — Datenbank **und** die 125 Storage-Objekte. Vollersatz statt Abgleich: derselbe Lauf, dasselbe Ergebnis, unabhängig davon, wie oft er lief. Ein zeilenweiser Abgleich müsste für jede künftig angelegte Tabelle `upsert`-treu bleiben und würde still veralten.",
      "**Der Auszug ist eine Datei und bleibt eine.** Jeder Lauf legt den Auszug ausserhalb des Arbeitsbaums ab, bevor er DEV anfasst. Damit entsteht die Sicherung für den PROD-Neuaufbau als Nebenprodukt jedes Spiegels statt als zweites Werkzeug, das niemand pflegt.",
      "**Ein ausdrücklicher Nachbereitungsschritt** stellt her, was DEV braucht und PROD nicht kennt: die drei `@fbcdemo.com`-Zugänge und die `staff_roles`. Ohne ihn nimmt der erste Vollersatz die dokumentierten Demo-Zugänge mit.",
      "**Nur auf Zuruf, kein Nachtlauf.** Jeder Lauf verwirft, woran auf DEV gerade gearbeitet wird. Ein Zeitplan kommt in Frage, wenn sich der Lauf von Hand bewährt hat — und ist ausdrücklich nicht Teil dieses Changes.",
      '**BREAKING (Spec, nicht Code):** `deployment-environments` fordert heute, das DEV/DEMO-Projekt trage „ausschließlich Demo-Daten". Diese Anforderung wird gebrochen und muss geändert werden, nicht umgangen.',
      "**Die Richtung ist einseitig und wird erzwungen.** PROD ist ausschließlich Quelle. Ein Lauf, der in die Gegenrichtung schriebe, ist kein Bedienungsfehler, sondern Datenverlust an echten Mitgliedern.",
    ],
  },
  {
    slug: "2026-08-14-add-member-onboarding",
    datum: "2026-08-14",
    titel: "add-member-onboarding",
    linear: null,
    aenderungen: [
      '**„Später"** vertagt. Der Merker wird **nicht** gesetzt, die Strecke erscheint beim nächsten Besuch der Startseite wieder und setzt beim ersten noch leeren Feld an.',
      '**„Überspringen"** beendet endgültig. Es **warnt vorher** — positiv formuliert, nicht drohend: ohne Kategorien findet einen der Kompass-Filter nicht, und das ist der Weg, auf dem die anderen Mitglieder einen finden.',
    ],
  },
  {
    slug: "2026-08-13-resolve-anon-name-masking",
    datum: "2026-08-13",
    titel: "resolve-anon-name-masking",
    linear: null,
    aenderungen: [
      "Die anonyme Verdeckung wird als das beschrieben, was sie ist — **zwei Ebenen**, Daten und Anzeige, mit der Datenebene als der tragenden.",
      "Die **tatsächliche Preisgabe an eingeloggte Konten** wird ausgesprochen: volle Namen sind heute Verzeichnisdaten für jedes aktivierte Konto, `basic` eingeschlossen. Bisher stand das nirgends.",
      'Das stufenweise Auflösen bleibt **benannt offen**, mit Zeiger auf `finish-ui-polish`, statt als „pending" ohne Adresse zu schweben.',
      "Das Geländer für neue anon-Flächen wird auf das zurückgenommen, was der vorhandene Test **wirklich** hält.",
    ],
  },
  {
    slug: "2026-08-13-header-member-search",
    datum: "2026-08-13",
    titel: "header-member-search",
    linear: null,
    aenderungen: [
      "Ab 2 Zeichen, entprellt (300 ms), erscheint ein Dropdown mit den ersten 5 Treffern: Avatarbild, Name, Berufsbezeichnung.",
      "Klick auf einen Treffer öffnet dessen Profil.",
      'Enter oder „Alle Ergebnisse" führt auf `/mitglieder` mit **übernommenem** Suchbegriff.',
      "Vollständig mit der Tastatur bedienbar: ↑ ↓ Enter Escape.",
      "Auf dem Telefon öffnet ein Lupensymbol die Suche.",
    ],
  },
  {
    slug: "2026-08-13-drift-gate-folgt-dem-frontend",
    datum: "2026-08-13",
    titel: "drift-gate-folgt-dem-frontend",
    linear: null,
    aenderungen: [
      "`drift-gate` löst sein Ziel aus derselben Quelle auf wie der Build — dem `VITE_SUPABASE_URL` der Infisical-Umgebung, mit der `deploy` baut — statt `SUPABASE_DB_URL_PROD` fest zu verdrahten. Kein Treffer gegen eine der beiden versionierten Ref-Dateien heißt rot.",
      "`drift-gate` wartet auf `migrate-dev` (`needs`), weil es das Live-Projekt sonst vor dessen Migration misst und an der eigenen Reihenfolge scheitert.",
      "Der Migrationsstand des jeweils **anderen** Projekts wird weiterhin gemessen, aber nur berichtet, nicht blockiert — Ersatz für die Frühwarnung, die durch die Umstellung des Ziels entfällt.",
      "Jeder Lauf nennt das gemessene Projekt im Protokoll, auch der unauffällige.",
    ],
  },
  {
    slug: "2026-08-13-clean-up-profile-page",
    datum: "2026-08-13",
    titel: "Profil aufräumen: vertagte Kompass-Widgets und Demo-Daten raus (AGE-539)",
    linear: null,
    aenderungen: [
      '**Die zwei Demo-Datensätze werden ersatzlos entfernt.** `DEMO_POSTS` und `DEMO_NETWORK` verschwinden samt der Zweige, die sie rendern, und samt der „Demo"-Abzeichen daneben.',
      '**Vier Kompass-Widgets werden aus `/profil` ausgebaut**: „Mein Erfolgsradar", „Meine Auszeichnungen", „Meine Ziele", „Meine Entwicklung". Die Komponenten **bleiben im Code** und werden nur nicht mehr gerendert — dieselbe Bauweise wie bei Matching (AGE-450). Keine Spalte, keine Migration, kein Datenverlust: `potential_score`, `dev_focus`, `goals` bleiben unangetastet.',
      "**Die MATCHES-Kachel im Profilkopf entfällt** (`ProfilAnsichtPage.tsx:68`). Matching ist bewusst unerreichbar; ein Zähler, der immer 0 zeigt, macht die Abwesenheit sichtbar, statt sie zu verbergen.",
      '**„Meine Interessen" bleibt** — begründet in der Datenlage: `interests` wird aus dem WordPress-Feld „Hobbys" befüllt, 38 von 70 Mitgliedern haben etwas eingetragen. Hobbys sind die einzige nicht-geschäftliche Ebene im Profil.',
      '**„Meine Beiträge" bleibt mit einladendem Leerzustand.** Beiträge gibt es wirklich (`posts`, C8) — der Leerzustand verspricht also keine Funktion, die niemand gebaut hat, und deckt sich mit dem bestehenden Szenario „Present capability renders an empty state".',
      "**Leere Widgets rendern gar nicht** — neue Leitregel für die eigene Profilseite, mit genau einer Ausnahme: Bereiche, die zum Ausfüllen einladen.",
      '**„Mitglied seit" erscheint nur mit Datum.** Heute steht dort bei fehlendem `member_since` ein Gedankenstrich (`formatDate` liefert „—"); nach dem Import träfe das 18 von 70.',
      '`MatchingWidget` (`kontakte-widgets.tsx:198`) und `MeineChancenPage.tsx` — beide sind **bereits unerreichbar**. `MatchingWidget` wird von keiner Seite gerendert (AGE-450 nahm es aus `KontaktePage`), und `MeineChancenPage` wird von **nichts** importiert. Die Issue vermutet „Aktive Matches" auf `/kontakte`; dort steht in Wahrheit der `DEMO_NETWORK`-Block, den dieser Change entfernt.',
      "`ImpactWidget` (`profil-widgets.tsx:160`) mit seiner erfundenen Verlaufskurve — ebenfalls von nichts importiert. Entscheidung Donald, 13.08.: unerreichbar heißt ignorieren.",
    ],
  },
  {
    slug: "2026-08-13-add-profile-address-fields",
    datum: "2026-08-13",
    titel: "C6a — Adressfelder im Profil (AGE-537)",
    linear: null,
    aenderungen: [
      "**Fünf Adressspalten auf `public.profile_contacts`** — `street`, `postal_code`, `city`, `state`, `country` (Vorgabe `DE`). Bewusst *nicht* auf `profiles`: dort wäre die Anschrift für jedes eingeloggte Mitglied lesbar.",
      "**Die Anschrift erbt die Freigabe von E-Mail und Telefon.** Kein neuer Sichtbarkeitsbegriff und keine zusätzliche Policy — `contacts_select_self_or_released` gibt die Zeile weiterhin nur an den Eigentümer und an eine Gegenseite mit angenommener Kontaktanfrage, beide Zweige an `is_activated()` gebunden.",
      "**Erster Mitglieder-Schreibpfad auf `profile_contacts` überhaupt.** Bis heute schreibt dort nur `admin_update_profile()`; ein Mitglied kann seine eigene Kontakt-E-Mail und Telefonnummer nicht pflegen. Der neue Kontaktblock im Profil-Editor deckt deshalb **Adresse plus `email` und `phone`** ab (Entscheidung Donald, 13.08.). Die Policies `profile_contacts_insert_own` / `_update_own` existieren bereits — es fehlt nur die Oberfläche.",
      "**`admin_update_profile()`** bekommt die fünf Felder in Weißliste und Upsert. `admin_get_profile()` liefert sie durch `to_jsonb(c)` bereits mit.",
      "**Die Anschrift erscheint in der Profilansicht** im vorhandenen Kontaktbereich, mit demselben Hinweis wie Telefon und E-Mail.",
      '**Kuratierte Branchenliste** in `src/config/`, wie die Kompass-Kategorien: Das Editor-Feld `branche` wird eine Auswahl statt eines Freitextfelds, und eine reine Zuordnungsfunktion bildet den WordPress-Freitext „Business" auf diese Werte ab. Aufgerufen wird sie erst von C10; hier entsteht sie mit ihren Tests.',
      '**`region` bleibt die Regionalgruppe** („FBC Standort") und wird nicht mit der Anschrift vermischt.',
    ],
  },
  {
    slug: "2026-08-13-academy-lite-and-feed-weave",
    datum: "2026-08-13",
    titel: "Academy aus geteilten Videos, und Events weben sich in den Feed",
    linear: "AGE-533",
    aenderungen: [],
  },
  {
    slug: "2026-08-12-overlay-scroll-lock-and-focus-trap",
    datum: "2026-08-12",
    titel: "overlay-scroll-lock-and-focus-trap",
    linear: "AGE-529",
    aenderungen: [],
  },
  {
    slug: "2026-08-12-events-content",
    datum: "2026-08-12",
    titel: "events-content",
    linear: "AGE-531",
    aenderungen: [
      "**Vier neue Spalten auf `public.events`**: `description` (text), `ends_at` (timestamptz), `cover_path` (text, `unique`), `topics` (text[]). `unique (cover_path)` ist nicht Kosmetik — die Sichtbarkeitsfunktion des Buckets schlägt das Event über genau diese Spalte nach, und zwei Zeilen auf denselben Pfad machten die Antwort mehrdeutig (dieselbe Begründung wie `post_media.storage_path`).",
      "**`cover_path` wird an den Host gebunden**, an zwei Stellen. Der Plan-Review hat hier eine echte Lücke gefunden: die Upload-Policy beweist Eigentum nur, während das **Objekt** entsteht — wer danach die Spalte schreibt, prüft niemand. Ein Mitglied könnte den verwaisten Pfad eines fremden `members`-Events an sein eigenes `public`-Event hängen, und `anon` signierte ein Bild, das nie öffentlich war. C7 wehrt genau diesen Angriff in `create_post_with_media` ab (`20260812090000_post_media.sql:214–240`); hier fehlte er. Geschlossen wird er **schreibend** (`events_write_host` verlangt im `with_check`, dass das erste Pfadsegment die eigene uid ist) **und lesend** (`event_cover_lesbar` verlangt, dass es der `host_id` des gefundenen Events entspricht) — die zweite Hälfte deckt Zeilen ab, die die erste nie gesehen hat.",
      "**`starts_at` wird `not null`.** Kein Bestand steht im Weg — und das ist gemessen, nicht angenommen: DEV 9 Events / 0 ohne Termin, **PROD 0 Events** (`viwntbodrtqxgmqyxluh`, read-only Vorabmessung mit `scripts/probe-c8-starts-at-preflight.ts`). Folge im Frontend: `EventForm` muss den Termin **verlangen**, sonst scheitert das Anlegen erst am `insert`.",
      "**Constraint `ends_at is null or ends_at > starts_at`.** Das Ende bleibt optional; ist es gesetzt, liegt es nach dem Beginn.",
      "**Neue RPC `public.event_attendees(uuid)`**, `SECURITY DEFINER`, `stable`, `set search_path = ''`. Liefert `profile_id` und `status` der **angemeldeten** Teilnehmer eines Events, das der Aufrufer sehen darf, nur für ein aktiviertes Konto und nur für Profile, die öffentlich und aktiviert sind. `execute` nur für `authenticated` — ausgeloggt gibt es keine Teilnehmer, auch nicht bei einem öffentlichen Event.",
      '**Ein eigener Query-Key für die Teilnehmerreihe.** `fetchAttendees` und `attendeesKey` bleiben unangetastet: sie liefern `registrationId`, `checked_in` und `rating` und werden von **zwei** privilegierten Stellen benutzt — `HostTools` **und** `RatePanel` (`EventDetailPage.tsx:226`). Die erste Fassung dieses Changes behauptete „nur `HostTools`"; das war schlicht falsch. Die neue, schmalere Projektion bekommt deshalb einen getrennten Schlüssel und wird nach An- und Abmeldung mit invalidiert, statt sich einen Cache mit einer anderen Datenform zu teilen.',
      "**Neuer privater Bucket `event-covers`**, 2 MiB, nur `image/webp`, mit SELECT-Policy über die neue Funktion `public.event_cover_lesbar(text)` sowie INSERT/UPDATE/DELETE im eigenen `{uid}/`-Pfad hinter `public.is_activated()` — wörtlich das Muster der drei bestehenden Buckets. 2 MiB statt 1 MiB wie bei `post-media`: das Titelbild ist ein Querformat-Header, nicht eine von sechs Kacheln; `covers` (C6) trägt aus demselben Grund 2 MiB.",
      "**Titelbild-Upload im Formular** über den bestehenden `AvatarCropper` mit `aspect = 3` (er nimmt den Wert bereits als Prop entgegen, `AvatarCropper.tsx:67`), Ausgabe WebP wie beim Hintergrundbild.",
      "**`EventForm` um vier Felder**, alle optional außer dem jetzt verlangten Termin: Beschreibung (mehrzeilig), Ende, Titelbild, Themen. Damit hat das Formular **ein** Pflichtfeld mehr als heute (Termin), nicht vier.",
      "**Übersicht auf drei Kacheln** (`lg:grid-cols-3`) und Kachel nach Mockup: Titelbild mit Datumsmarke, Typ-Marke, Titel, Von–Bis, Ort, Teilnehmerzahl, Knopf.",
      '**Detailseite nach Mockup**: Titelbild als Header mit Datumsmarke, Titel und Typ, Von–Bis, Ort, Beschreibung, Themen, Veranstalter mit Bild und Verlinkung, Teilnehmerreihe (fünf Gesichter + „+n"), Anmeldeknopf mit Kapazität und Warteliste, ähnliche Events. **Ohne Session bleiben Veranstalter und Teilnehmerreihe leer** — die Bestandsanforderung „Ohne Session löst die Eventliste keine Hosts auf" (AGE-530) gilt unverändert, und `event_attendees` trägt für `anon` kein `execute`. Die Seite bleibt erreichbar; nur die Anreicherung entfällt, und die Konsole bleibt frei von `42501`.',
    ],
  },
  {
    slug: "2026-08-12-event-detail-layout",
    datum: "2026-08-12",
    titel: "event-detail-layout",
    linear: "AGE-531",
    aenderungen: [
      '**Kartenlayout nach Mockup.** Hero-Karte mit Titelbild, Marken, Titel, Veranstalter und dem Anmelde-Feld rechts; darunter eine Reihe aus „Details", „Themen" und „Veranstalter"; darunter „Beschreibung" neben „Teilnehmer". Auf schmalen Fenstern stapelt alles wie bisher.',
      '**Der Veranstalter bekommt eine eigene Karte** mit Bild, Name, Rolle und Firma, Kurzbiografie und „Profil ansehen" — statt einer Zeile am Fuß. Die Felder kommen aus `profiles_public` (`company`, `roles`, `short_bio`), das `hostsFor` ohnehin schon abfragt; es werden nur drei Spalten mehr ausgewählt.',
      '**Sichtbarkeit als Satz.** Der „Details"-Block sagt „Offen für alle Mitglieder" bzw. „Nur für Mitglieder" statt gar nichts. Das Mockup führt diese Zeile, und sie beantwortet eine Frage, die sich beim Anmelden stellt.',
      '**„Änderungen vorbehalten."** unter den Themen und **„Alle Events anzeigen →"** neben „Ähnliche Events" — beides steht im Mockup und kostet nichts.',
      '**Brotkrume** „Events › Titel" statt „← Zu allen Events", wie im Mockup.',
    ],
  },
  {
    slug: "2026-08-12-anon-skips-author-enrichment",
    datum: "2026-08-12",
    titel: "anon-skips-author-enrichment",
    linear: "AGE-530",
    aenderungen: [
      "**`src/lib/feed.ts`** — `fetchAuthors` nimmt die bereits vorhandene Profil-Kennung entgegen und gibt ohne sie eine leere Karte zurück, ohne zu fragen. `fetchFeed` reicht sein `uid` durch.",
      "**`src/lib/events.ts`** — `hostsFor` überspringt ohne Session **beide** Hälften, `profiles_public` **und** `partners`. `fetchEvents` und `fetchEvent` tragen `uid` bereits.",
      '**`partners` ist ebenfalls nur für `authenticated` lesbar** — `20260715140000_explicit_grants.sql:62` erteilt `select` ausschließlich dort, und `openspec/specs/partners/spec.md` führt es als Anforderung („Anonymous partner read is denied"). Die erste Fassung wollte die Partner-Hälfte ausdrücklich weiterlaufen lassen und hätte damit den zweiten 401 stehen gelassen, während der Vorschlag „Konsole fehlerfrei" verspricht. Ausgeloggt erscheint ein Event künftig **ohne jede Host-Angabe**.',
      "**`fetchComments` fliegt raus.** `comments` trägt sein `select` ebenfalls nur für `authenticated` (`explicit_grants.sql:67`); ausgeloggt gibt es keine Kommentare zu lesen, also auch keine Autoren anzureichern. Ein Test, der einen erfolgreichen anonymen Kommentarabruf vortäuscht, prüfte einen Zustand, den es nicht gibt.",
    ],
  },
  {
    slug: "2026-08-12-activity-media-and-tags",
    datum: "2026-08-12",
    titel: "activity-media-and-tags",
    linear: "AGE-528",
    aenderungen: [
      "**Neue Tabelle `public.post_media`** (`id`, `post_id`, `storage_path`, `sort`, `width`, `height`, `created_at`), FK auf `posts` mit `on delete cascade`. Bewusst eine Tabelle und **kein** `posts.media jsonb`: mehrere Bilder brauchen Reihenfolge und einzelne Löschbarkeit.",
      "**Neuer privater Bucket `post-media`**, 1 MiB, nur `image/webp`. Er ist der erste Bucket dieses Projekts mit **einer SELECT-Policy** — bei `avatars` und `covers` fehlt sie bewusst, weil dort der Bucket öffentlich ist. Hier trägt genau diese Policy die Zugriffskontrolle.",
      "**Vier Storage-Policies**: SELECT für `anon` (nur Objekte von `public`-Beiträgen) und für `authenticated` (dasselbe Prädikat wie `posts_select_by_visibility`), INSERT/UPDATE/DELETE nur im eigenen `{uid}/`-Pfad und nur mit `public.is_activated()` — wie in beiden bestehenden Buckets.",
      '**Neue Tabelle `public.tags`** (`key`, `label`, `sort`, `active`) als redaktionelle Liste, mit Startbefüllung von **15 Tags — elf Themen aus der Filterliste des Mockups plus vier Formate** (Liste und Begründung in `design.md`; ausdrücklich *nicht* die Kompass-Kategorien, das sind Matching-Kategorien und es sind 14, nicht elf). `key` ist per Constraint kleingeschrieben und tippbar — sonst zerfällt derselbe Tag in zwei Werte, je nachdem ob er geklickt oder als `#Wort` getippt wurde. **Keine Verknüpfungstabelle:** `posts.hashtags text[]` bleibt wie es ist und hält beide Sorten. Ein Chip gilt als kuratiert, wenn sein Wert in `tags` vorkommt. Damit bleibt die bestehende Filterlogik (`.contains("hashtags", [hashtag])`, `src/lib/feed.ts:294`) unangetastet, und die Migration ist ein Insert statt einer Umstrukturierung.',
      "**Tag-Doppelanzeige behoben**: Hashtag-Segmente in `PostBody` rendern als normaler Text, die Chip-Reihe bleibt die eine Darstellung. Dazu ein Regressionstest — `CommunityFeed.tsx` hat heute **keine** Testdatei, dieser Change legt die erste an.",
      '**Neuer Client-Helfer `shrinkToWebp`**: Bilder werden vor dem Hochladen clientseitig auf Maximalkante 1600 px verkleinert und nach WebP konvertiert (Qualität 0,82), höchstens sechs pro Beitrag. `AvatarCropper` bleibt unangetastet — dort ist die Rechnung ein erzwungener „cover"-Zuschnitt (`cropGeometry`, `AvatarCropper.tsx:27–59`), der von jedem Foto etwas abschneiden würde.',
      "**Composer nach Mockup**: Text, Bilder, Video-Link, Tag-Auswahl aus der kuratierten Liste plus Freitext, Sichtbarkeit.",
      '**Beitragskarte nach Mockup** inklusive Bildlayout: eins groß, zwei nebeneinander, drei und mehr als Raster mit „+n".',
      "**Tag-Filterleiste** über die kuratierten Tags, zusätzlich zum bestehenden Hashtag-Filter.",
      '**Feed wird seitenweise geladen**: 20 statt 50, mit „Mehr laden". Heute liest `fetchFeed` 50 Zeilen ohne Paginierung (`src/lib/feed.ts:293`); mit Bildern wird diese Zahl zu einer stillen Kappung.',
    ],
  },
  {
    slug: "2026-08-11-signup-password-after-confirmation",
    datum: "2026-08-11",
    titel: "Das Passwort entsteht nach der Bestätigung, nicht davor (AGE-527)",
    linear: null,
    aenderungen: [
      "**Die Registrierung erhebt kein Passwort mehr.** Name und Adresse genügen. Das Passwort entsteht dort, wo es hingehört: beim Einlösen des Bestätigungslinks. Die Selbstregistrierung geht damit genau den Weg, den importierte Mitglieder schon gehen — ein Weg statt zwei.",
      "**Das erfolgreiche Setzen bekommt einen eigenen Bildschirm.** Er sagt, dass das Passwort gesetzt ist, und führt zum Login: sofort per Knopf oder von selbst nach zehn Sekunden. Für **beide** Zwecke der Seite — Aktivierung und Passwort-Zurücksetzen.",
    ],
  },
  {
    slug: "2026-08-11-profile-cover-and-admin-edit",
    datum: "2026-08-11",
    titel: "profile-cover-and-admin-edit",
    linear: "AGE-498",
    aenderungen: [
      "**`profiles.cover_url text`** — die einzige neue Spalte auf `profiles`, und die einzige neue Spalte im Client-UPDATE-Grant.",
      "**Neue private Tabelle `public.profile_legacy`** (1:1 zu `profiles`) mit `paid_until date`, `legacy_tier text`, `legacy_price numeric`, `legacy_source_id text`. **Kein Client-Grant, RLS an, für Mitglieder unsichtbar.** `legacy_source_id` bekommt einen partiellen Unique-Index über den getrimmten Wert, damit der Import wiederholbar ist.",
      "**`cover_url` wird an `profiles_public` angehängt.** Ohne das rendert das Hintergrundbild auf `/p/:id` nie — die Seite liest die öffentliche Projektion. **Angehängt, nicht eingefügt**: `create or replace view` erlaubt neue Spalten nur am Ende.",
      "**Neuer Storage-Bucket `covers`** mit drei Policies nach dem Muster von `avatars_insert_own` / `_update_own` / `_delete_own` — inklusive `is_activated()`, das die avatars-Policies seit C3 tragen.",
      "**Vier `SECURITY DEFINER`-Funktionen** statt einer: `admin_update_profile` (schreiben), `admin_get_profile` und `admin_find_profile` (lesen — ohne die ist der Anlassfall unerreichbar, siehe unten), und der Audit-Schreiber.",
      "**Tabelle `public.admin_audit`**, von beiden Schreibwegen befüllt.",
      "**Edge Function `admin-change-email`** ändert die Login-Adresse in `auth.users`. Das geht nicht aus der Datenbank heraus.",
      "**Frontend**: `AvatarCropper` bekommt ein Seitenverhältnis (3:1) und wird wiederverwendet; der bestehende Profil-Editor wird mit einer Ziel-ID wiederverwendet; die Profilansicht folgt dem Mockup.",
    ],
  },
  {
    slug: "2026-08-11-activation-mail-on-signup",
    datum: "2026-08-11",
    titel: "Aktivierungsmail bei der Selbstregistrierung (AGE-526)",
    linear: null,
    aenderungen: [
      "Eine erfolgreiche Selbstregistrierung löst den Versand des Bestätigungslinks **ohne weiteres Zutun** aus. Der Knopf auf dem Aktivierungsbildschirm bleibt als zweiter Weg bestehen.",
      "Der Aktivierungsbildschirm zeigt den Zustand, der wirklich eingetreten ist. Heute gibt der Client-Aufruf `void` zurück und verschluckt den Status der Function; ein `rate_limited` sieht damit aus wie ein Versand. Der Status wird durchgereicht.",
      "**Neu: eine profilübergreifende Grenze von 100 Token-Ausgaben pro Stunde** auf dem sitzungsgebundenen Weg. Sie greift nur für Profile, die **jünger als 10 Minuten** sind, also für den Registrierungsschwall. Ein Mitglied, dessen Konto älter ist, kommt über den Knopf immer durch — die Sperre eines frischen Kontos löst sich nach zehn Minuten von selbst.",
    ],
  },
  {
    slug: "2026-08-09-member-activation-flow",
    datum: "2026-08-09",
    titel: "Mitglieder-Aktivierung: das Passwort allein ist wertlos",
    linear: "AGE-495",
    aenderungen: [],
  },
  {
    slug: "2026-08-09-lock-activation-token-race",
    datum: "2026-08-09",
    titel: "lock-activation-token-race",
    linear: "AGE-507",
    aenderungen: [
      "**Beide ausgebenden RPCs sperren die Profilzeile, bevor sie prüfen** — `select … for update of p` an der ersten Abfrage von `issue_activation_token` (gültige Fassung: `20260808150000`) und `request_own_activation_token` (gültige Fassung: die Erstdeklaration `20260806090000`, seither nie neu deklariert). Damit steht die Prüfung nicht mehr auf einem Snapshot, der zwischen Prüfung und Schreiben veraltet.",
      "**Nur `profiles` wird gesperrt, nicht die mitgejointe `auth.users`-Zeile.** Schreibweise und Präzedenzfall stehen im Repo: `20260716120000_stripe_upgrade.sql:29` serialisiert nebenläufige Upgrades desselben Nutzers auf demselben Join-Muster.",
      "**Beide Wege sperren in derselben Reihenfolge** — erst `profiles`, dann `activation_tokens`. Deadlockfrei per Konstruktion, und das gehört in den Migrationskopf, nicht in jemandes Gedächtnis.",
      "**Der `23505`-Zweig aus 8.1 bleibt.** Die Sperre macht ihn zum Gürtel neben den Hosenträgern, ersetzt ihn nicht: er deckt weiterhin ab, was an den RPCs vorbei einfügt.",
      '**`request_own_activation_token` bekommt kein Schutzfenster** — nur die Sperre. Das Fenster fehlt dort mit Absicht: Subjekt ist die Sitzung, „schick mir einen neuen Link" soll wirken. Die Sperre behebt dort etwas anderes: zwei gleichzeitige eigene Anfragen können heute eine **rohe** `unique_violation` auslösen — die Function hat, anders als ihre Schwester, keinen Handler —, die `resend-activation` als 5xx durchreicht.',
      "**Eine Sonde belegt den Wettlauf deterministisch** (8.9), im Muster von `scripts/probe-activation-gate.ts`, mit einem Unterschied: sie verweigert jedes Ziel außer `127.0.0.1`.",
      "**`serializable` für diese Transaktionen.** Verschiebt den Fehler nur: der Verlierer bekommt `40001` und damit wieder einen Fehler, wo `pending` die richtige Antwort ist — und die Wiederholung müsste in `send-activation` gebaut werden, das absichtlich immer `202` antwortet.",
      "**Das Schutzfenster in `request_own_activation_token` nachziehen.** Wäre eine Verhaltensänderung des Hauptwegs, die niemand verlangt hat: das angemeldete Mitglied darf sich einen neuen Link schicken lassen.",
      "**Den `23505`-Zweig durch die Sperre ersetzen.** Er deckt einen anderen Fall ab — Einfügen an den RPCs vorbei. Ihn zu entfernen tauschte einen bewiesenen Schutz gegen einen neuen.",
      "**`dblink` installieren, um den Wettlauf in pgTAP nachzustellen.** Eine Extension, die beliebige ausgehende Verbindungen öffnen kann, landete damit für einen Test dauerhaft in PROD.",
    ],
  },
  {
    slug: "2026-08-08-ci-deploy-edge-functions",
    datum: "2026-08-08",
    titel: "ci-deploy-edge-functions",
    linear: "AGE-506",
    aenderungen: [
      "Neuer Job **`functions`** in `deploy.yml`. Läuft auf `main`, hängt an denselben Vorbedingungen wie `deploy` (`migrate-dev`, `drift-gate`).",
      "Er leitet aus den geänderten Dateien des Merges ab, **welche** Functions betroffen sind, und deployt **nur diese** — auf DEV **und** PROD.",
      "Nach dem Deploy liest er `supabase functions list` je Projekt und protokolliert Version und Prüfsumme; übersprungene Functions werden **namentlich** genannt.",
      "Neues Skript `scripts/changed-functions.logic.ts` (reine Ableitung, unter Test) plus ein dünner CLI-Aufruf.",
      "`docs/secrets.md` und die Aufgabe 11.2 (f) werden auf den neuen Zustand gebracht: die Merkregel wird durch den Job ersetzt, nicht ergänzt.",
    ],
  },
  {
    slug: "2026-08-05-split-prod-dev-supabase",
    datum: "2026-08-05",
    titel: "Supabase trennen: neues PROD-Projekt, altes wird DEV/DEMO",
    linear: null,
    aenderungen: [],
  },
  {
    slug: "2026-08-05-mvp-scope-navigation",
    datum: "2026-08-05",
    titel: "Auf den Go-Live-Umfang zurückschneiden, Kompass als Filter",
    linear: null,
    aenderungen: [],
  },
  {
    slug: "2026-08-04-refine-shell-and-page-heads",
    datum: "2026-08-04",
    titel: "Shell am Rand, Themes nur aufs Chrome, Seitenköpfe mit Bild",
    linear: "AGE-499",
    aenderungen: [],
  },
  {
    slug: "2026-08-04-redesign-blue-theme-system",
    datum: "2026-08-04",
    titel: "Blue theme system: two themes, one accent, member-chosen",
    linear: "AGE-492",
    aenderungen: [],
  },
];
